chore: improve about panel and sidenavs
openline-ai/openline-customer-os pull request #2787
Opened 2023-07-21 15:14 UTC by acalinica

## Proposed changes

## Changes

What types of changes does your code introduce?  _Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Build related changes
- [ ] Documentation Update (if none of the other choices apply)
- [ ] Other (please describe below)

## Additional context

2023-07-21 15:16 UTC, Kasia9090 requested changes

2023-07-21 15:16 UTC, Kasia9090 commented on packages/apps/spaces/app/components/Sidenavs/OrganizationSidenav.tsx
> +        label='Organization Name Lorem ipsum sin dolor amit sumit'
Lorem ipsum :)

2023-07-21 15:16 UTC, Kasia9090 commented on packages/apps/spaces/app/components/Sidenavs/OrganizationSidenav.tsx
> +            Organizationabcdefg
copy :)

2023-07-21 15:17 UTC, acalinica commented on packages/apps/spaces/app/components/Sidenavs/OrganizationSidenav.tsx
> +        label='Organization Name Lorem ipsum sin dolor amit sumit'
Thing is I need the value of the Tenant which I'm not sure where to pick it from.

2023-07-21 15:17 UTC, acalinica commented on packages/apps/spaces/app/components/Sidenavs/OrganizationSidenav.tsx
> +            Organizationabcdefg
Same here...

2023-07-21 15:37 UTC, Kasia9090 commented on packages/apps/spaces/app/components/Sidenavs/OrganizationSidenav.tsx
> +        label='Organization Name Lorem ipsum sin dolor amit sumit'
import { useTenantName } from '@spaces/hooks/useTenant';

You can use this hook

2023-07-21 17:25 UTC, edifirut submitted a review, later dismissed

2023-07-22 08:41 UTC, edifirut approved these changes

2023-07-24 07:53 UTC, Kasia9090 approved these changes

2023-07-24 07:54 UTC, merged