feat: add meeting preview modal
openline-ai/openline-customer-os pull request #3459
Opened 2023-08-30 08:46 UTC by acalinica

## Proposed changes

closes #3431 

## Changes

What types of changes does your code introduce?  _Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Build related changes
- [ ] Documentation Update (if none of the other choices apply)
- [ ] Other (please describe below)

## Additional context

2023-08-31 08:52 UTC, Kasia9090 requested changes

2023-08-31 08:52 UTC, Kasia9090 commented on packages/apps/spaces/app/organizations/[id]/components/Timeline/events/meeting/MeetingPreviewModal.tsx
> +import { utcToZonedTime, format } from 'date-fns-tz';
Move those to DateUtils class, it's to keep those fuctions after fasade to ensure easiness on changing library if we'll ever want to do that for some reason

2023-08-31 08:52 UTC, Kasia9090 commented on packages/apps/spaces/app/organizations/[id]/components/Timeline/events/meeting/MeetingPreviewModal.tsx
> +  const participants = event?.attendedBy
This does not include all possible types of participants. Please use helper function from timeline utils to ensure all possible types of participants are handled in consistent way

2023-08-31 13:16 UTC, Kasia9090 requested changes

2023-08-31 13:16 UTC, Kasia9090 commented on packages/apps/spaces/app/organizations/[id]/components/Timeline/events/utils.ts
> +export const getParticipantEmailOrName = (
Do we prefer email over name in stubs as well? I think we need two functions one that prefers name (stubs, other types of interaction event participants) and one that prefer email over name for meeting modal view and possibly other events in the future

2023-08-31 13:16 UTC, Kasia9090 commented on packages/apps/spaces/app/organizations/[id]/components/Timeline/events/meeting/MeetingPreviewModal.tsx
> +    if (event?.createdBy?.[0]?.__typename === 'ContactParticipant') {
Event participant can be also user or organization

2023-08-31 13:18 UTC, acalinica commented on packages/apps/spaces/app/organizations/[id]/components/Timeline/events/utils.ts
> +export const getParticipantEmailOrName = (
Yes, I've just checked before pushing that for Meetings we prefer emails first and names after. For other cases what can I say, I initially kept the code co-located only to meet stuff, now it became more generic which I would've not.

2023-08-31 13:19 UTC, acalinica commented on packages/apps/spaces/app/organizations/[id]/components/Timeline/events/utils.ts
> +export const getParticipantEmailOrName = (
@steynviljoen67 can confirm this to you.

2023-08-31 13:39 UTC, steynviljoen67 commented on packages/apps/spaces/app/organizations/[id]/components/Timeline/events/utils.ts
> +export const getParticipantEmailOrName = (
In stubs, prefer name first. If no name is available, show email.

2023-09-01 08:09 UTC, Kasia9090 approved these changes

2023-09-01 08:15 UTC, merged